//! Strategy runner HTTP routes — protocol-agnostic signal generation + execution.
//!
//! The StrategyRunner evaluates HarnessConfig rules against live candle data and
//! produces TradeSignals. These signals can be:
//!   - Auto-executed (rule mode): signal → trade, no human/agent in the loop
//!   - Returned to the agent (advisory mode): agent decides whether to act
//!   - Used for paper-trade validation: compare agent decisions against rule signals
//!
//! The execution path is protocol-agnostic — signals specify an asset and direction,
//! and the caller (or auto-executor) routes through the appropriate protocol
//! (/execute with target_protocol, or /hyperliquid/order, or /clob/*, etc.).
//!
//! Endpoints:
//!   POST /strategy/tick — feed candle, get signals (+ optional auto-execute)
//!   POST /strategy/config — update harness config (from evolve-strategy.js)
//!   GET /strategy/state — current runner state

use axum::extract::State;
use axum::http::StatusCode;
use axum::{
    Json, Router,
    routing::{get, post},
};
use serde::{Deserialize, Serialize};
use std::sync::Arc;
use tokio::sync::RwLock;

use trading_runtime::backtest::runner::{RunnerOutput, StrategyRunner};
use trading_runtime::backtest::types::{Candle, HarnessConfig};

use crate::MultiBotTradingState;

// ── Shared runner state ─────────────────────────────────────────────────────

static RUNNER: std::sync::LazyLock<RwLock<Option<StrategyRunner>>> =
    std::sync::LazyLock::new(|| RwLock::new(None));

// ── Types ───────────────────────────────────────────────────────────────────

#[derive(Deserialize)]
pub struct TickRequest {
    /// The candle to evaluate
    pub candle: Candle,
    /// Target protocol for auto-execution (e.g., "hyperliquid", "uniswap_v3").
    /// If set, signals are auto-executed via that protocol.
    /// If omitted, signals are returned without execution (advisory mode).
    #[serde(default)]
    pub target_protocol: Option<String>,
}

#[derive(Serialize)]
pub struct TickResponse {
    /// Signals generated by the rule engine
    pub signals: RunnerOutput,
    /// Execution results (only if target_protocol was set)
    pub executions: Vec<ExecutionResult>,
    /// What the agent should consider doing (human-readable)
    pub advisory: Vec<String>,
}

#[derive(Serialize)]
pub struct ExecutionResult {
    pub asset: String,
    pub action: String,
    pub protocol: String,
    pub success: bool,
    pub detail: String,
}

#[derive(Serialize)]
pub struct StrategyState {
    pub initialized: bool,
    pub harness_version: u32,
    pub max_positions: usize,
    pub entry_threshold: f64,
    pub num_entry_rules: usize,
    pub num_exit_rules: usize,
}

// ── Handlers ────────────────────────────────────────────────────────────────

async fn tick(
    State(state): State<Arc<MultiBotTradingState>>,
    Json(req): Json<TickRequest>,
) -> Result<Json<TickResponse>, (StatusCode, String)> {
    // Initialize runner if needed
    {
        let reader = RUNNER.read().await;
        if reader.is_none() {
            drop(reader);
            let mut writer = RUNNER.write().await;
            if writer.is_none() {
                *writer = Some(StrategyRunner::new(HarnessConfig::default()));
                tracing::info!("StrategyRunner initialized with default config");
            }
        }
    }

    let mut runner = RUNNER.write().await;
    let runner = runner.as_mut().unwrap();

    let signals = runner.on_candle(&req.candle);
    let mut executions = Vec::new();
    let mut advisory = Vec::new();

    // Generate advisory messages for the agent
    for entry in &signals.entries {
        advisory.push(format!(
            "ENTRY SIGNAL: {} {:?} (strength={:.0}%, size={:.0}%, SL={:.1}%, TP={:.1}%)",
            entry.asset,
            entry.direction,
            entry.strength * 100.0,
            entry.size_fraction * 100.0,
            entry.stop_loss_pct.unwrap_or(0.0),
            entry.take_profit_pct.unwrap_or(0.0),
        ));
    }
    for exit in &signals.exits {
        advisory.push(format!(
            "EXIT SIGNAL: {} reason={:?}",
            exit.asset, exit.reason,
        ));
    }

    // Auto-execute if target_protocol is specified
    if let Some(ref protocol) = req.target_protocol {
        if !signals.is_empty() {
            match protocol.as_str() {
                "hyperliquid" => {
                    if let Ok(client) = super::hyperliquid::get_hl_client(&state) {
                        for entry in &signals.entries {
                            let result = execute_hl_entry(client, entry, &req.candle.token).await;
                            executions.push(result);
                        }
                        for exit in &signals.exits {
                            let result = execute_hl_exit(client, exit).await;
                            executions.push(result);
                        }
                    }
                }
                _ => {
                    // For other protocols, return signals as advisory —
                    // the agent calls /execute with the appropriate target_protocol
                    advisory.push(format!(
                        "Auto-execution not implemented for {protocol}. Use /execute with target_protocol={protocol}."
                    ));
                }
            }
        }
    }

    Ok(Json(TickResponse {
        signals,
        executions,
        advisory,
    }))
}

async fn update_config(
    Json(config): Json<HarnessConfig>,
) -> Result<Json<serde_json::Value>, (StatusCode, String)> {
    if let Err(errors) = config.validate() {
        return Err((
            StatusCode::BAD_REQUEST,
            format!("Invalid config: {}", errors.join(", ")),
        ));
    }

    let version = config.version;
    let mut writer = RUNNER.write().await;
    if let Some(ref mut r) = *writer {
        r.update_harness(config);
    } else {
        *writer = Some(StrategyRunner::new(config));
    }
    tracing::info!(version, "Harness config updated");

    Ok(Json(
        serde_json::json!({ "status": "ok", "version": version }),
    ))
}

async fn get_state() -> Json<StrategyState> {
    let reader = RUNNER.read().await;
    match reader.as_ref() {
        Some(runner) => {
            let h = runner.harness();
            Json(StrategyState {
                initialized: true,
                harness_version: h.version,
                max_positions: h.max_positions,
                entry_threshold: h.entry_threshold,
                num_entry_rules: h.entry_rules.len(),
                num_exit_rules: h.exit_rules.len(),
            })
        }
        None => Json(StrategyState {
            initialized: false,
            harness_version: 0,
            max_positions: 0,
            entry_threshold: 0.0,
            num_entry_rules: 0,
            num_exit_rules: 0,
        }),
    }
}

// ── HL execution helpers ────────────────────────────────────────────────────

use trading_runtime::backtest::runner::ExitSignal;
use trading_runtime::backtest::runner::TradeSignal;
use trading_runtime::hyperliquid::{AssetId, HlOrderType, PlaceOrderRequest};

async fn execute_hl_entry(
    client: &trading_runtime::hyperliquid::HyperliquidClient,
    signal: &TradeSignal,
    _token: &str,
) -> ExecutionResult {
    let is_buy = matches!(
        signal.direction,
        trading_runtime::backtest::types::Direction::Long
    );

    // Get current price for SL/TP computation
    let current_price: f64 = client
        .get_mids()
        .await
        .ok()
        .and_then(|m| m.get(&signal.asset).and_then(|p| p.parse().ok()))
        .unwrap_or(0.0);

    if current_price <= 0.0 {
        return ExecutionResult {
            asset: signal.asset.clone(),
            action: "entry".into(),
            protocol: "hyperliquid".into(),
            success: false,
            detail: "Cannot fetch price".into(),
        };
    }

    let sl_pct = signal.stop_loss_pct.unwrap_or(5.0);
    let tp_pct = signal.take_profit_pct.unwrap_or(10.0);
    let sl_price = if is_buy {
        current_price * (1.0 - sl_pct / 100.0)
    } else {
        current_price * (1.0 + sl_pct / 100.0)
    };
    let tp_price = if is_buy {
        current_price * (1.0 + tp_pct / 100.0)
    } else {
        current_price * (1.0 - tp_pct / 100.0)
    };

    let entry = PlaceOrderRequest {
        asset: AssetId::Symbol(signal.asset.clone()),
        is_buy,
        size: format!("{:.4}", signal.size_fraction * 100.0),
        order_type: HlOrderType::Market,
        reduce_only: false,
        cloid: None,
    };
    let sl = PlaceOrderRequest {
        asset: AssetId::Symbol(signal.asset.clone()),
        is_buy: !is_buy,
        size: entry.size.clone(),
        order_type: HlOrderType::StopLoss {
            trigger_price: format!("{:.2}", sl_price),
            is_market: true,
        },
        reduce_only: true,
        cloid: None,
    };
    let tp = PlaceOrderRequest {
        asset: AssetId::Symbol(signal.asset.clone()),
        is_buy: !is_buy,
        size: entry.size.clone(),
        order_type: HlOrderType::TakeProfit {
            trigger_price: format!("{:.2}", tp_price),
            is_market: true,
        },
        reduce_only: true,
        cloid: None,
    };

    match client.place_bracket(&entry, Some(&sl), Some(&tp)).await {
        Ok(resp) => {
            tracing::info!(asset = %signal.asset, dir = ?signal.direction, price = current_price, "Entry executed");
            ExecutionResult {
                asset: signal.asset.clone(),
                action: format!("{:?}", signal.direction),
                protocol: "hyperliquid".into(),
                success: true,
                detail: format!("{:?}", resp),
            }
        }
        Err(e) => ExecutionResult {
            asset: signal.asset.clone(),
            action: format!("{:?}", signal.direction),
            protocol: "hyperliquid".into(),
            success: false,
            detail: e,
        },
    }
}

async fn execute_hl_exit(
    client: &trading_runtime::hyperliquid::HyperliquidClient,
    signal: &ExitSignal,
) -> ExecutionResult {
    let account = client.get_account().await;
    let pos = account
        .as_ref()
        .ok()
        .and_then(|a| a.positions.iter().find(|p| p.asset == signal.asset));

    let Some(pos) = pos else {
        return ExecutionResult {
            asset: signal.asset.clone(),
            action: format!("{:?}", signal.reason),
            protocol: "hyperliquid".into(),
            success: false,
            detail: "No position to close".into(),
        };
    };

    let size: f64 = pos.size.parse().unwrap_or(0.0);
    let close = PlaceOrderRequest {
        asset: AssetId::Symbol(signal.asset.clone()),
        is_buy: size < 0.0,
        size: format!("{:.8}", size.abs()),
        order_type: HlOrderType::Market,
        reduce_only: true,
        cloid: None,
    };

    match client.place_order(&close).await {
        Ok(resp) => {
            tracing::info!(asset = %signal.asset, reason = ?signal.reason, "Exit executed");
            ExecutionResult {
                asset: signal.asset.clone(),
                action: format!("{:?}", signal.reason),
                protocol: "hyperliquid".into(),
                success: true,
                detail: format!("{:?}", resp),
            }
        }
        Err(e) => ExecutionResult {
            asset: signal.asset.clone(),
            action: format!("{:?}", signal.reason),
            protocol: "hyperliquid".into(),
            success: false,
            detail: e,
        },
    }
}

// ── Router ──────────────────────────────────────────────────────────────────

pub fn multi_bot_router() -> Router<Arc<MultiBotTradingState>> {
    Router::new()
        .route("/strategy/tick", post(tick))
        .route("/strategy/config", post(update_config))
        .route("/strategy/state", get(get_state))
}
